version: '3.8'

services:
  ubuntu:
    image: ubuntu:18.04
    build: ./docker/ubuntu
    container_name: ubuntu_18_04
    volumes:
      - ./shared_folder:/shared_folder
      - ssh-keys:/root/.ssh
    networks:
      - ubuntu_network
    ports:
      - "2222:22"
    stdin_open: true # docker run -i
    tty: true        # docker run -t

networks:
  ubuntu_network:
    name: ubuntu_network
  
volumes:
  ssh-keys: